version: '3'
services:
  node:
    restart: always 
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
  mongo:
    image: mongo
    ports:
      - 27017:27017 
    volumes:
       - ./data:/data/db
