pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                echo "building..."
                sh '../NotesApp/init.sh' 
            }
        }

        stage('Test'){
            steps{
                echo "testing..."
            }
        }

        stage('Deploy'){
            steps{
                echo "deploying..."
            }
        }
    }
}